// example/src/js/App.jsx
import React, { useState } from 'react';

export default function App() {
	const [count, setCount] = useState(0);

	function handleClick() {
		setCount(count + 1);
	}

	return (
		<div className="space-y-2">
			<img className="mx-auto w-12 h-12" src="dist/assets/react.svg" alt="React Logo" />
			<p>
				React count is <code>`{count}`</code>
			</p>
			<button className="bg-blue-700 px-4 py-1 rounded font-bold text-blue-50 text-sm" onClick={handleClick}>
				Increment
			</button>
		</div>
	);
}

// example/src/js/App.svelte
<script>
	let count = 0;

	function handleClick() {
		count += 1;
	}
</script>

<div class="space-y-2">
	<img class="mx-auto w-12 h-12" src="dist/assets/svelte.svg" alt="Svelte Logo" />
	<p>Svelte count is <code>`{count}`</code></p>
	<button class="bg-blue-700 px-4 py-1 rounded font-bold text-blue-50 text-sm" on:click={handleClick}
		>Increment</button
	>
</div>
